#!/bin/sh

_CUR_SCRIPT='/etc/profile'

export PATH='/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin'

unset _PREV_IFS
if [ ! -z "$IFS" ] ; then
    _PREV_IFS=$IFS
fi

IFS=':'
for _CUR_PATH in $PATH ; do
    if [ ! -e "$_CUR_PATH" ] ; then
        printf '!!! %s : %s\n' "$_CUR_SCRIPT" "$_CUR_PATH does not exist" 1>&2
        continue
    fi

    if [ ! -d "$_CUR_PATH" ] ; then
        printf '!!! %s : %s\n' "$_CUR_SCRIPT" "$_CUR_PATH is not a directory" 1>&2
        continue
    fi
done
unset _CUR_PATH
unset IFS

if [ ! -z "$_PREV_IFS" ] ; then
    IFS=$_PREV_IFS
fi
unset _PREV_IFS


export USER=${USER:-root}
export HOME=${HOME:-/root}


if [ -f /proc/sys/kernel/hostname ] ; then
    HOSTNAME=$( cat /proc/sys/kernel/hostname )
fi
export HOSTNAME=${HOSTNAME:=localhost}


export PS1='\u@\h:\w \$ '


_PROFILE_D='/etc/profile.d'
if [ -d "$_PROFILE_D" ]; then
    for _CUR_FILE in "$_PROFILE_D"/*.sh ; do
        if [ -r "$_CUR_FILE" ] ; then
            . "$_CUR_FILE"
        fi
    done
    unset _CUR_FILE
fi
unset _PROFILE_D

unset _CUR_SCRIPT

