#!/bin/sh
[ -f /etc/banner ] && cat /etc/banner

export PATH=/usr/bin:/usr/sbin:/bin:/sbin
export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
export HOME=${HOME:-/root}
export PS1='\u@\h:\w\$ '

[ -x /bin/more ] || alias more=less
[ -x /usr/bin/vim ] && alias vi=vim || alias vim=vi

[ -z "$KSH_VERSION" -o \! -s /etc/mkshrc ] || . /etc/mkshrc

[ -x /usr/bin/arp ] || arp() { cat /proc/net/arp; }
[ -x /usr/bin/ldd ] || ldd() { LD_TRACE_LOADED_OBJECTS=1 $*; }

export PATH=/usr/local/bin:/usr/local/sbin:$PATH
export TERM=${TERM%-256color}

OPTLOCAL_ENV='/opt/local/lib/common.sh'
[ -f "$OPTLOCAL_ENV" ] && \
  alias optlocalenv=". $OPTLOCAL_ENV"
unset OPTLOCAL_ENV

